# Python CircleCI 2.0 configuration file
#
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: "45f7d4f96f83afb3d71c0da51d990af175a791f77c4355835741692f7897e1a7"
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.8
      - image: circleci/postgres:11.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            python3 -m venv venv
            . venv/bin/activate
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > venv/bin/cc-test-reporter
            chmod +x venv/bin/cc-test-reporter
      - run:
          name: install dependencies
          command: |
            . venv/bin/activate
            pip install wagtail
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pip install coverage
            coverage run ./runtests.py
            coverage report
            coverage xml
            cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?
